List<String> statelist = [
  'Andaman and Nicobar Islands',
  '	Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chandigarh ',
  'Chhattisgarh',
  'Dadra and Nagar Havel',
  'Daman and Diu',
  'Delhi',
  'Goa',
  'Gujrat',
  'Haryana',
  'Himachal Pradesh',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Sikkim',
  'Meghalya',
  'Mizoram',
];
